[build]
command = "yarn rw deploy netlify"
publish = "web/dist"
functions = "api/dist/functions"

[dev]
  # To use [Netlify Dev](https://www.netlify.com/products/dev/),
  # install netlify-cli from https://docs.netlify.com/cli/get-started/#installation
  # and then use netlify link https://docs.netlify.com/cli/get-started/#link-and-unlink-sites
  # to connect your local project to a site already on Netlify
  # then run netlify dev and our app will be accessible on the port specified below
  framework = "redwoodjs"
  # Set targetPort to the [web] side port as defined in redwood.toml
  targetPort = 8910
  # Point your browser to this port to access your RedwoodJS app
  port = 8888

## @MARK Is this respected? 👇
[[redirects]]
  from = "/bazinga"
  to = "/login"
  status = 307
  force = true
  query = {path = ":path"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[[redirects]]
  from = "/api"
  to = "/.netlify/functions"
